[package]
name = "cz"
version = "0.1.0"
edition = "2021"
description="""
A encoder/decoder for CZ# image files used in
[RealLive Engine](https://www.pcgamingwiki.com/wiki/Engine:RealLive).
"""

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0.59"
png = "0.17.13"
image = "0.25.1"
