[package]
name = "cz"
version = "0.1.0"
edition = "2021"
description="""
A encoder/decoder for CZ# image files used in the LUCA System Engine.
"""

[features]
png = ["dep:image"]

[dependencies]
byteorder = "1.5"
thiserror = "1.0"
imagequant = "4.3"
rgb = "0.8"

# Only active on feature "png"
image = { version = "0.25", default-features = false, features = ["png"], optional = true }
