[package]
name = "lbee-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.2.4"
image = { version = "0.24.6", features = ["webp", "webp-encoder"] }
png = "0.17.8"
sdl2 = { version = "0.35.2", features = ["gfx"] }
sdl2-sys = "0.35.2"
