[workspace]
resolver = "2"
members = [
    "cz",
    "experimental",
    "luca_pak",
]

[workspace.package]
authors = ["G2"]

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.production]
inherits = "release"
lto = true
strip = true
codegen-units = 1
panic = "abort"
