[package]
name = "pak_explorer"
edition = "2021"
version = "0.1.1"
description = """
A simple GUI for exploring and making modifications to LUCA System PAK files.
"""
license = "AGPL-3.0"
authors.workspace = true
publish = false

[dependencies]
cz = { path = "../cz/", features = ["png"] }
eframe = { version = "0.28.1", default-features = false, features = ["wayland", "x11", "accesskit", "default_fonts", "wgpu"] }
egui_extras = "0.28.1"
luca_pak = { path = "../luca_pak/" }
rfd = "0.14.1"

[lints]
workspace = true
