[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.4", features = ["derive", "unicode"] }
cz = { path = "../cz" }
image = { version = "0.25.1", default-features = false, features = ["png"] }
walkdir = "2.5.0"
