[package]
name = "utils"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors.workspace = true

[[bin]]
name = "czutil"

[[bin]]
name = "pakutil"

[dependencies]
cz = { path = "../cz/", features = ["png"] }
luca_pak = { path = "../luca_pak/" }

image = { version = "0.25", default-features = false, features = ["png"] }
clap = { version = "4.5.9", features = ["derive"] }

[lints]
workspace = true
