[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
cz = { path = "../cz" }
fontdue = { version = "0.8.0", features = ["parallel"] }
image = "0.25.1"
walkdir = "2.5.0"
