[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cz = { path = "../cz" }
image = "0.25.1"
walkdir = "2.5.0"
